package ch.pitaya.pitaya.authorization;

public enum AuthCode {

	// dummy authcode forbidding everything
	NONE,

	// user & firm management
	USER_CREATE, USER_CHANGE_PASSWORD, FIRM_MODIFY,
	FIRM_READ_ROLES, FIRM_CHANGE_ROLES(FIRM_READ_ROLES),
	FIRM_MANAGE_CLIENTS,

	// case management
	CASE_READ, FIRM_CASE_CREATE(CASE_READ), CASE_MODIFY(CASE_READ),
	CASE_CHANGE_ROLES, CASE_READ_ROLES,

	// file management
	FILE_READ, CASE_CREATE_FILE(FILE_READ), FILE_EDIT(FILE_READ), FILE_UPDATE(FILE_READ), FILE_DELETE(FILE_READ),
	FILE_READ_ROLES, FILE_CHANGE_ROLES,

	// profiles
	BASIC_USER(CASE_READ, FILE_READ),

	// admin profiles
	USER_ADMIN(USER_CREATE, USER_CHANGE_PASSWORD, FIRM_MODIFY, FIRM_CHANGE_ROLES, FIRM_MANAGE_CLIENTS), //
	CASE_ADMIN(FIRM_CASE_CREATE, CASE_MODIFY, CASE_READ_ROLES, CASE_CHANGE_ROLES), //
	FILE_ADMIN(CASE_CREATE_FILE, FILE_EDIT, FILE_UPDATE, FILE_DELETE, FILE_READ_ROLES, FILE_CHANGE_ROLES), //
	ADMIN(USER_ADMIN, CASE_ADMIN, FILE_ADMIN);

	// enum internals
	public final AuthCode[] parents;

	AuthCode(AuthCode... parents) {
		this.parents = parents;
	}

}
